# Site settings
title: Mangakah Personal Site
email: mangakah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal web site of Carlos Santos, a freelance web developer and aspiring enterpreneur. Here I present myself, do some blogging and give some freebies away.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mangakah_
github_username:  mangakah

# Build settings
markdown: kramdown
highlighter: pygments

# Outputting
permalink:     none
paginate_path: /page:num
